[TestTable]
IsAllowMultipleInstanceRunning=true
IsConfirmBeforeDeleteFile=false
LongDefaultWindowMode=1
LongDefaultImageDisplayMode=1
IsCenterBigImageByDefault=true
IsEnlargeSmallImageByDefault=false
LongSortFileBy=2
IsDescendingSort=false
LongBehaviorOnReachingFirstLastFile=0
DoubleDragMultiplier=0.57
DoubleAnimationSpan=0.98
DoubleExtendRenderRatio=0.66
DoubleReRenderWaitTime=1.67
LongFileInfo=0
LongEXIFInfo=2
StringWindowBackgroundColor='(255,255,255)'
StringImageBackgroundColor='(0,0,0)'
LongImageEnlargingAlgorithm=1
LongImageShrinkingAlgorithm=2
LongImageDoublingAlgorithm=0
StringImageEditorPath='.\'
StringLanguage='chinese'
